import java.util.Scanner;
public class Shop {
    private static String[] tooltips =
    {
    "Note: The 'machine gun' is neither automatic nor particularly effective.",
    "\"MIDDLE EAST MIDDLE EAST MIDDLE EAST MIDDLE EAST\" - Tyler Engola",
    "One of the test subjects is named John TSN, odd name but you don't judge",
    "\"Casting\" - Tyler Engola",
    "During the development of this game, we spent 30 minutes debugging the method to catch falling items. The problem was that it was called catch().",
    "TSN Chapter 2 is predicted to come out some time before the heat death of the universe",
    "Is something supposed to go here?",
    "The day on the log when you first launch the game comes from the [TEST SUBJECT NAME] social media.",
    "In this game, The General has flags for arms. This is a reference to Tyler Engola being in color guard. (point and laugh)",
    "The Pirated copy of this game comes with extra bombs.",
    "This tooltip was supposed to be replaced before release. Oops.",
    "Butts in seats",
    "If you haven't already, make sure your phone is in the Cell Hotel",
    "If you can't beat this game, your future as a [CREATIVE GAME NAME] player is over, and your high score will be deposited directly in my circular file.",
    "public         static          void   main ( String[]    args  ) 🤓",
    "\"UGHHHHHH THIS IS SO COMPLICATED\"",
    "If I made a plan for a metro system would you guys support it?",
    "Exception in thread \"TSN Chapter 2\" java.lang.NullPointerException",
    "did you hear taylor swift owns her albums now?",
    "Compiling shaders... wait, this game has shaders?",
    "Fun fact: catch() is not a good name for the method that handles caught items.",
    "if (gameBroken) { blame(\"Tyler Engola\";) }",
    "Why does it always crash on Tuesdays? Nobody knows",
    "This game is like a homeless man's tent: Small and full of bugs.",
    "This tooltip was generated by ChatGPT.",
    "Every time you read this, it takes a few minutes off my lifespan",
    "Hint: If you're stuck, try playing better.",
    "Why are you still here? Finals are in less than a week.",
    "You just lost the game",
    "This game contains no microtransactions. Yet.",
    "Think, Test Subject, Think! What will you have after 500 playthroughs?",
    "The cake was real. You just weren't invited.",
    "Please remain calm. The explosion is mostly decorative.",
    "If you experience any hallucinations, please disregard them. They are not part of the game.",
    "This sentence is false",
    "As a reminder, I'm lightspeeding you at this very moment",
    "The dev team was replaced by highly-trained raccoons. You may notice no difference.",
    ":3",
    "Mom said it's my turn on the debug console.",
    "Spaghetti code approved by Gordon Ramsay",
    "Somewhere, a for loop cries itself to sleep.",
    "All hail our mechanical overlords. Expecially Zesty Tylerbot 3000.",
    "Warning: Entering an atmosphere made entirely of JPEG files",
    "Atlas Pass V3 required to play this game",
    "Chicken jockey",
    "Error 418: I have a headache",
    "Loading... Loading... Loading... Loading... Loading... Loading... Nevermind.",
    "Error 594923813709907: My parents are getting divorced",
    "The leaderboard has achieved sentience. Please be nice.",
    "Legend says that a strange smell has been spreading through Langley's classrooms for decades. That's a Lott of time.",
    "Remember to breathe through your mouth during PALS",
    "finals week is my final week, what???",
    "Input \"Yes\" to affirm"
    };
    
    private boolean isOpen;
    public Shop()
    {
        isOpen = false;
    } 
    
    public void displayShop(Player p)
    {
        isOpen = true;
        System.out.print("\033[H\033[2J");
        
        System.out.println("███▓▒░░           [SHOP]          ░░▒▓███");
        System.out.println("=========================================");
        System.out.println("ˢʰᵒᵖ ˢᵖᵒⁿˢᵒʳᵉᵈ ᵇʸ ᵐᵘⁿᶜʰ ᶦⁿᶜ®");
        System.out.println();
        System.out.println("   [1] health pack     [2] repair kit    ");
        System.out.println();
        System.out.println("   [3] instructions    [4] quit game     ");
        System.out.println();
        System.out.println("🔧 : " + p.getBuildItems());
        System.out.println("=========================================");
        System.out.println(tooltips[(int) (Math.random() * tooltips.length)]);
    }
    
    public void closeShop() {
        System.out.print("\033[H\033[2J");
        isOpen = false;
    }
    
    public boolean isOpen()
    {
        return isOpen;
    }
    
    public void printInstructions() {
        Scanner in = new Scanner(System.in);
        System.out.println("\n[INITIALIZING CONTROL INTERFACE]");
        wait(2000);
        System.out.println("Use [A] to shift left. [D] to shift right.");
        wait(500);
        System.out.println("Manual input required. Press [ENTER] after each command.");
        System.out.println("\n[PRESS ENTER TO CONTINUE, OR E TO SKIP]");
        if (in.nextLine().equalsIgnoreCase("e")) return;
    
        System.out.println("[VITAL READOUTS]");
        wait(1000);
        System.out.println("◉  Left: [CHASSIS INTEGRITY] - if it hits 0, your core fails.");
        System.out.println("◉  Right: [TEST CHAMBER STABILITY] - restore this to reassert control.");
        wait(500);
        System.out.println("Both values will appear beneath the grid.");
        System.out.println("\n[PRESS ENTER TO CONTINUE]");
        in.nextLine();
    
        System.out.println("Fragments will begin to fall from above: scrap, tech, and corruption.");
        wait(500);
        System.out.println("Position yourself to intercept, dodge, or endure.");
        wait(500);
        System.out.println("Let too many payloads hit the floor, and you'll feel it.");
        System.out.println("\n[PRESS ENTER TO CONTINUE]");
        in.nextLine();
    
        System.out.println("[LOADING ITEM CATALOG]");
        wait(2000);
        System.out.println("🔧  | [WRENCH]: Currency. Collect to repair or heal. Will deal damage if dropped.");
        System.out.println("🕒  | [CHRONO-FRAGMENT]: Slows drop speed.");
        System.out.println("🧲  | [POLAR CORE]: Creates a magnetic field powerful enough to increase your pickup range, while obscuring the vision near you.");
        wait(1000);
        System.out.println("💣  | [BOMB SHELL]: Highly volatile. Impact = devastation.");
        System.out.println("🕸  | [CYBER-WEB]: Shuts down your movement for a few cycles.");
        System.out.println("👾  | [STRANGE EXPLOIT]: Obscures visual feed with fog.");
        System.out.println("💻  | [DENUVO CRACK]: TSN Anti-Piracy Screen.");
        wait(1000);
        System.out.println("🎰  | [UNKNOWN CONSTRUCT]: Results... unpredictable.");
        wait(500);
        System.out.println("\n[PRESS ENTER TO CONTINUE]");
        in.nextLine();
    
        System.out.println("Occasionally, you'll see a countdown.");
        wait(500);
        System.out.println("When it reaches zero: [SHOP INTERFACE] will unlock.");
        wait(500);
        System.out.println("Spend your wrenches - restore health, repair the chamber.");
        wait(500);
        System.out.println("The system won't let you leave with unspent parts.");
    }
    
    public static void wait(int ms) {
        try {
            Thread.sleep(ms);
        }
        catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
    }
}
